project:
  title: "my_blog"
  output-dir: docs

docs:
    navbar:
      right:
        - about.qmd
        - icon: github
          href: https://github.com/Lilonno/my_blog1
        - icon: twitter
          href: https://twitter.com

format:
    html:
      theme: cosmo
      css: styles.css
