<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ONNO Lilou">
<meta name="dcterms.date" content="2024-03-06">

<title>my_blog - Exercice1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">my_blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exercice1</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>ONNO Lilou </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 6, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="exercice-1" class="level1">
<h1>Exercice 1</h1>
<p><strong>Library</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'stringr' a été compilé avec la version R 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Question 1 :</strong> Créez un script .R intitulé exercice.R.</p>
<p><strong>Question 2 :</strong> Lisez le fichier téléchargé (ou directement depuis le site, cf aide plus bas) avec la fonction read.table. Le résultat sera affecté à l’objet de nom data_ex. Le jeux de données contient 4 colonnes. Quels sont les noms et la nature des colonnes ? Combien de lignes contient la data.frame ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://data.iledefrance.fr/api/explore/v2.1/catalog/datasets/paris-2024-sites-olympiques-et-paralympiques-franciliens/exports/csv"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_ex <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">fill =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_ex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            geo_point                                 nom
1 48.841319, 2.253076                    Parc des Princes
2 48.924388, 2.359871                     Stade de France
3  48.92467, 2.332428                   Village olympique
4  48.815115, 2.08208               Château de Versailles
5 48.944207, 2.424716                  Village des médias
6 48.944643, 2.408258 Terrain des Essences - La Courneuve
    sites_olympiques_paralympiques
1                   Site olympique
2 Site olympique,Site paralympique
3                                 
4 Site olympique,Site paralympique
5                                 
6                Site paralympique
                                               sports
1                                            Football
2                    Athlétisme,Para athlétisme,Rugby
3                                                    
4 Sports équestres,Para équitation,Pentathlon moderne
5                                                    
6                                     Para athlétisme</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_ex) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  geo_point             nom            sites_olympiques_paralympiques
 Length:31          Length:31          Length:31                     
 Class :character   Class :character   Class :character              
 Mode  :character   Mode  :character   Mode  :character              
    sports         
 Length:31         
 Class :character  
 Mode  :character  </code></pre>
</div>
</div>
<p><em>Nous avons une base de donnée, avec 4 colonnes :</em></p>
<ul>
<li><p><em>geo_point : qui représente la localisation d’où ce passe les JO avec la latitude et la longitude en fonciton des sports</em></p></li>
<li><p><em>nom : nom de l’endroit ou ce passe la compétititon</em></p></li>
<li><p><em>sites_olympiques_paralympiques : si c’est un site olympique ou paralympique ou les deux</em></p></li>
<li><p><em>sports : enfin le nom d’un ou des sports partiquées.</em></p></li>
</ul>
<p><strong>Question 3 :</strong> Combien y a t’il de sites olympiques ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_ex<span class="sc">$</span>sites_olympiques_paralympiques)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                                   Site olympique 
                               2                               10 
Site olympique,Site paralympique                Site paralympique 
                              16                                3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nb_sites_olympiques <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"Site olympique"</span>, data_ex<span class="sc">$</span>sites_olympiques_paralympiques))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>nb_sites_olympiques</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26</code></pre>
</div>
</div>
<p><em>Nous avons donc 26 sites olympiques</em></p>
<p><strong>Question 4 :</strong> Combien y a t’il de sites paralympiques ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_ex<span class="sc">$</span>sites_olympiques_paralympiques)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                                   Site olympique 
                               2                               10 
Site olympique,Site paralympique                Site paralympique 
                              16                                3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>nb_sites_paralympique <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"Site paralympique"</span>, data_ex<span class="sc">$</span>sites_olympiques_paralympiques))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>nb_sites_paralympique</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19</code></pre>
</div>
</div>
<p><em>Nous avons donc 19 sites paralympique</em></p>
<p><strong>Question 5 :</strong> Quels sont les sites qui accueillent plusieurs disciplines sportives ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#création d'une autre BDD avec que les multisports</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sites_multisports <span class="ot">&lt;-</span> data_ex[<span class="fu">sapply</span>(<span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">&gt;</span><span class="dv">1</span>, ]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Nous avons une bdd avec que les endroits associés aux sports pratiqués. Chaque sports étant séparé par une virgule, nous avons pris dans la colonne sport, toute les lignes qui avait donc une virgule ou plus. </span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sites_multisports<span class="sc">$</span>sites_olympiques_paralympiques)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                  Site olympique Site olympique,Site paralympique 
                               3                               16 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>nb_sites_olympiques_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"Site olympique"</span>, sites_multisports<span class="sc">$</span>sites_olympiques_paralympiques))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>nb_sites_olympiques_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19</code></pre>
</div>
</div>
<p><em>Nous avons a travers ce code, l’information que nous avons 3 sites olympiques qui acceuille plusieurs discipline et 16 sites olympiques et paralympique qui acceuille plsueiurs disciplines sportives</em></p>
<p><strong>Question 7 :</strong> Quel(s) site(s) accueille(nt) le plus de disciplines différentes ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>deux_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>deux_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>trois_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>trois_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>quatres_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>quatres_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>cinq_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">5</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>cinq_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>six_sports <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>six_sports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#le max de sport est 4</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>sites_plus_sports <span class="ot">&lt;-</span> data_ex[</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sapply</span>(<span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>sports), <span class="st">","</span>), length) <span class="sc">==</span> <span class="dv">4</span>, ]</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sites_plus_sports<span class="sc">$</span>sites_olympiques_paralympiques)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                  Site olympique Site olympique,Site paralympique 
                               1                                7 </code></pre>
</div>
</div>
<p><em>les sites olympique ET paralympiques, accueille le plus de discipline différentes</em></p>
<p><strong>Question 8 :</strong> Quel discipline aura lieu sur le plus grand nombre de sites ? Quels sont ces sites ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sports_nom_plus <span class="ot">&lt;-</span> data_ex <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sports =</span> <span class="fu">strsplit</span>(<span class="fu">as.character</span>(sports), <span class="st">", "</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(sports) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sports) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>sports_nom_plus<span class="sc">$</span>sports[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Athlétisme"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>sports_nom_plus<span class="sc">$</span>count[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p><em>La discipline qui revient le plus grand nombre de fois est l’athlétisme.</em></p>
<p><strong>Question 9 :</strong> A vol d’oiseau, quels sont les sites les deux sites les plus proches ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#on va regroupé les codes de longitude et latitude, divisé en deux colonnes X1 et X2</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>data_coordonnees <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">do.call</span>(<span class="st">'rbind'</span>, <span class="fu">strsplit</span>(<span class="fu">as.character</span>(data_ex<span class="sc">$</span>geo_point), <span class="st">','</span>)))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#on va les renommer</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data_coordonnees) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"latitude"</span>, <span class="st">"longitude"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co">#on va les réintégrer dans la bdd data_ex</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>data_ex <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data_ex, data_coordonnees)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co">#on va les mettre en valeur numérique pour la suite du code</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>data_ex<span class="sc">$</span>longitude <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data_ex<span class="sc">$</span>longitude)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>data_ex<span class="sc">$</span>latitude <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data_ex<span class="sc">$</span>latitude)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>coordonnees <span class="ot">&lt;-</span> data_ex[, <span class="fu">c</span>(<span class="st">"latitude"</span>, <span class="st">"longitude"</span>)]</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>noms_sites <span class="ot">&lt;-</span> data_ex<span class="sc">$</span>nom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>site1 <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>site2 <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>distance_min <span class="ot">&lt;-</span> <span class="cn">Inf</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">nrow</span>(coordonnees) <span class="sc">-</span> <span class="dv">1</span>)) {</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> (i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span><span class="fu">nrow</span>(coordonnees)) {</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">#on va convertire les noms des sites en minuscules, sinon le code ne marche pas</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    nom_site_i <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">trimws</span>(noms_sites[i]))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    nom_site_j <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">trimws</span>(noms_sites[j]))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Calculons la distance entre les sites que l'on va nomée i et j</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    distance <span class="ot">&lt;-</span> <span class="fu">distHaversine</span>(coordonnees[<span class="fu">c</span>(i, j), , <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Distance entre"</span>, nom_site_i, <span class="st">"et"</span>, nom_site_j, <span class="st">":"</span>, distance, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">#code pour essayer à chaque fois de toruver la distance la plus petite</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (distance <span class="sc">&lt;</span> distance_min) {</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>      distance_min <span class="ot">&lt;-</span> distance</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>      site1 <span class="ot">&lt;-</span> nom_site_i</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>      site2 <span class="ot">&lt;-</span> nom_site_j</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"Nouvelle distance trouvée :"</span>, site1, <span class="st">"et"</span>, site2, <span class="st">"avec distance :"</span>, distance_min, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Distance entre parc des princes et stade de france : 15056.74 mètres
Nouvelle distance trouvée : parc des princes et stade de france avec distance : 15056.74 mètres
Distance entre parc des princes et village olympique : 12805.62 mètres
Nouvelle distance trouvée : parc des princes et village olympique avec distance : 12805.62 mètres
Distance entre parc des princes et château de versailles : 19257.08 mètres
Distance entre parc des princes et village des médias : 22271.85 mètres
Distance entre parc des princes et terrain des essences - la courneuve : 20748.36 mètres
Distance entre parc des princes et colline d'elancourt : 32305.28 mètres
Distance entre parc des princes et grand palais : 7154.178 mètres
Nouvelle distance trouvée : parc des princes et grand palais avec distance : 7154.178 mètres
Distance entre parc des princes et invalides : 7089.976 mètres
Nouvelle distance trouvée : parc des princes et invalides avec distance : 7089.976 mètres
Distance entre parc des princes et site d'escalade du bourget : 21469.18 mètres
Distance entre parc des princes et pont d'iéna : 4578.563 mètres
Nouvelle distance trouvée : parc des princes et pont d'iéna avec distance : 4578.563 mètres
Distance entre parc des princes et arena bercy : 13964.85 mètres
Distance entre parc des princes et arena paris nord : 32963.04 mètres
Distance entre parc des princes et arena paris sud 6 (porte de versailles) : 4393.84 mètres
Nouvelle distance trouvée : parc des princes et arena paris sud 6 (porte de versailles) avec distance : 4393.84 mètres
Distance entre parc des princes et stade de la concorde : 8050.22 mètres
Distance entre parc des princes et stade yves du manoir : 9967.937 mètres
Distance entre parc des princes et arena champs de mars : 5470.767 mètres
Distance entre parc des princes et stade tour eiffel : 5104.351 mètres
Distance entre parc des princes et stade bmx de saint-quentin-en-yvelines : 25038.36 mètres
Distance entre parc des princes et arena la chapelle : 13723.99 mètres
Distance entre parc des princes et stade pierre de coubertin : 835.1916 mètres
Nouvelle distance trouvée : parc des princes et stade pierre de coubertin avec distance : 835.1916 mètres
Distance entre parc des princes et centre aquatique : 14612.97 mètres
Distance entre parc des princes et arena paris sud 1 (porte de versailles) : 3606.39 mètres
Distance entre parc des princes et arena paris sud 4 (porte de versailles) : 4198.314 mètres
Distance entre parc des princes et hôtel de ville de paris : 11082.65 mètres
Distance entre parc des princes et la défense arena : 6580.477 mètres
Distance entre parc des princes et stade nautique : 42731.87 mètres
Distance entre parc des princes et golf national : 22129.94 mètres
Distance entre parc des princes et vélodrome national de saint-quentin-en-yvelines : 24990.38 mètres
Distance entre parc des princes et stade roland garros : 1075.47 mètres
Distance entre parc des princes et clichy-sous-bois : 33564 mètres
Distance entre stade de france et village olympique : 3055.102 mètres
Distance entre stade de france et château de versailles : 33226.67 mètres
Distance entre stade de france et village des médias : 7547.578 mètres
Distance entre stade de france et terrain des essences - la courneuve : 5838.553 mètres
Distance entre stade de france et colline d'elancourt : 46203.55 mètres
Distance entre stade de france et grand palais : 8368.71 mètres
Distance entre stade de france et invalides : 8641.704 mètres
Distance entre stade de france et site d'escalade du bourget : 6894.111 mètres
Distance entre stade de france et pont d'iéna : 10747.83 mètres
Distance entre stade de france et arena bercy : 9759.047 mètres
Distance entre stade de france et arena paris nord : 18486.54 mètres
Distance entre stade de france et arena paris sud 6 (porte de versailles) : 13048.34 mètres
Distance entre stade de france et stade de la concorde : 7829.343 mètres
Distance entre stade de france et stade yves du manoir : 12270.26 mètres
Distance entre stade de france et arena champs de mars : 10206.54 mètres
Distance entre stade de france et stade tour eiffel : 10306.09 mètres
Distance entre stade de france et stade bmx de saint-quentin-en-yvelines : 39276.84 mètres
Distance entre stade de france et arena la chapelle : 2778.395 mètres
Distance entre stade de france et stade pierre de coubertin : 15123.54 mètres
Distance entre stade de france et centre aquatique : 494.5346 mètres
Nouvelle distance trouvée : stade de france et centre aquatique avec distance : 494.5346 mètres
Distance entre stade de france et arena paris sud 1 (porte de versailles) : 13286.85 mètres
Distance entre stade de france et arena paris sud 4 (porte de versailles) : 13103.5 mètres
Distance entre stade de france et hôtel de ville de paris : 7569.808 mètres
Distance entre stade de france et la défense arena : 14837.62 mètres
Distance entre stade de france et stade nautique : 31546.91 mètres
Distance entre stade de france et golf national : 37025.23 mètres
Distance entre stade de france et vélodrome national de saint-quentin-en-yvelines : 39217.24 mètres
Distance entre stade de france et stade roland garros : 15348.53 mètres
Distance entre stade de france et clichy-sous-bois : 20815.62 mètres
Distance entre village olympique et château de versailles : 30416.63 mètres
Distance entre village olympique et village des médias : 10500.75 mètres
Distance entre village olympique et terrain des essences - la courneuve : 8728.774 mètres
Distance entre village olympique et colline d'elancourt : 43340.21 mètres
Distance entre village olympique et grand palais : 6891.563 mètres
Distance entre village olympique et invalides : 7260.763 mètres
Distance entre village olympique et site d'escalade du bourget : 9898.861 mètres
Distance entre village olympique et pont d'iéna : 8874.43 mètres
Distance entre village olympique et arena bercy : 10855.43 mètres
Distance entre village olympique et arena paris nord : 21426.96 mètres
Distance entre village olympique et arena paris sud 6 (porte de versailles) : 11543.92 mètres
Distance entre village olympique et stade de la concorde : 6689.15 mètres
Distance entre village olympique et stade yves du manoir : 9219.952 mètres
Distance entre village olympique et arena champs de mars : 8576.444 mètres
Distance entre village olympique et stade tour eiffel : 8522.563 mètres
Distance entre village olympique et stade bmx de saint-quentin-en-yvelines : 36494.17 mètres
Distance entre village olympique et arena la chapelle : 4305.937 mètres
Distance entre village olympique et stade pierre de coubertin : 12998.42 mètres
Distance entre village olympique et centre aquatique : 2574.906 mètres
Distance entre village olympique et arena paris sud 1 (porte de versailles) : 11619.06 mètres
Distance entre village olympique et arena paris sud 4 (porte de versailles) : 11557.56 mètres
Distance entre village olympique et hôtel de ville de paris : 7833.045 mètres
Distance entre village olympique et la défense arena : 11881.1 mètres
Distance entre village olympique et stade nautique : 34540.4 mètres
Distance entre village olympique et golf national : 34471.37 mètres
Distance entre village olympique et vélodrome national de saint-quentin-en-yvelines : 36432.29 mètres
Distance entre village olympique et stade roland garros : 12948.41 mètres
Distance entre village olympique et clichy-sous-bois : 23865.88 mètres
Distance entre château de versailles et village des médias : 40755.46 mètres
Distance entre château de versailles et terrain des essences - la courneuve : 39064.07 mètres
Distance entre château de versailles et colline d'elancourt : 13072.8 mètres
Distance entre château de versailles et grand palais : 26258.12 mètres
Distance entre château de versailles et invalides : 26260.18 mètres
Distance entre château de versailles et site d'escalade du bourget : 40041.69 mètres
Distance entre château de versailles et pont d'iéna : 23746.69 mètres
Distance entre château de versailles et arena bercy : 33100.56 mètres
Distance entre château de versailles et arena paris nord : 51666.84 mètres
Distance entre château de versailles et arena paris sud 6 (porte de versailles) : 23288.04 mètres
Distance entre château de versailles et stade de la concorde : 27204.95 mètres
Distance entre château de versailles et stade yves du manoir : 22683.74 mètres
Distance entre château de versailles et arena champs de mars : 24697.14 mètres
Distance entre château de versailles et stade tour eiffel : 24279.13 mètres
Distance entre château de versailles et stade bmx de saint-quentin-en-yvelines : 6113.76 mètres
Distance entre château de versailles et arena la chapelle : 32522.1 mètres
Distance entre château de versailles et stade pierre de coubertin : 19639.37 mètres
Distance entre château de versailles et centre aquatique : 32738.84 mètres
Distance entre château de versailles et arena paris sud 1 (porte de versailles) : 22570.58 mètres
Distance entre château de versailles et arena paris sud 4 (porte de versailles) : 23109.51 mètres
Distance entre château de versailles et hôtel de ville de paris : 30339.66 mètres
Distance entre château de versailles et la défense arena : 18717.88 mètres
Distance entre château de versailles et stade nautique : 61925.84 mètres
Distance entre château de versailles et golf national : 7155.132 mètres
Distance entre château de versailles et vélodrome national de saint-quentin-en-yvelines : 6045.72 mètres
Distance entre château de versailles et stade roland garros : 18541.33 mètres
Distance entre château de versailles et clichy-sous-bois : 52780.3 mètres
Distance entre village des médias et terrain des essences - la courneuve : 1832.738 mètres
Distance entre village des médias et colline d'elancourt : 53746.49 mètres
Distance entre village des médias et grand palais : 15228.01 mètres
Distance entre village des médias et invalides : 15396.94 mètres
Distance entre village des médias et site d'escalade du bourget : 912.7678 mètres
Distance entre village des médias et pont d'iéna : 17774.34 mètres
Distance entre village des médias et arena bercy : 12818.29 mètres
Distance entre village des médias et arena paris nord : 10939.62 mètres
Distance entre village des médias et arena paris sud 6 (porte de versailles) : 19614.57 mètres
Distance entre village des médias et stade de la concorde : 14464.99 mètres
Distance entre village des médias et stade yves du manoir : 19523.96 mètres
Distance entre village des médias et arena champs de mars : 17057.13 mètres
Distance entre village des médias et stade tour eiffel : 17280.72 mètres
Distance entre village des médias et stade bmx de saint-quentin-en-yvelines : 46791.15 mètres
Distance entre village des médias et arena la chapelle : 8590.226 mètres
Distance entre village des médias et stade pierre de coubertin : 22230.22 mètres
Distance entre village des médias et centre aquatique : 8040.421 mètres
Distance entre village des médias et arena paris sud 1 (porte de versailles) : 20012.59 mètres
Distance entre village des médias et arena paris sud 4 (porte de versailles) : 19711.16 mètres
Distance entre village des médias et hôtel de ville de paris : 12687.31 mètres
Distance entre village des médias et la défense arena : 22369.47 mètres
Distance entre village des médias et stade nautique : 25263.98 mètres
Distance entre village des médias et golf national : 44375.48 mètres
Distance entre village des médias et vélodrome national de saint-quentin-en-yvelines : 46732.7 mètres
Distance entre village des médias et stade roland garros : 22674.64 mètres
Distance entre village des médias et clichy-sous-bois : 14034.31 mètres
Distance entre terrain des essences - la courneuve et colline d'elancourt : 52032.17 mètres
Distance entre terrain des essences - la courneuve et grand palais : 13794.37 mètres
Distance entre terrain des essences - la courneuve et invalides : 13993.97 mètres
Distance entre terrain des essences - la courneuve et site d'escalade du bourget : 1592.056 mètres
Distance entre terrain des essences - la courneuve et pont d'iéna : 16305.12 mètres
Distance entre terrain des essences - la courneuve et arena bercy : 12245.61 mètres
Distance entre terrain des essences - la courneuve et arena paris nord : 12699.39 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 6 (porte de versailles) : 18294.68 mètres
Distance entre terrain des essences - la courneuve et stade de la concorde : 13085.19 mètres
Distance entre terrain des essences - la courneuve et stade yves du manoir : 17701.84 mètres
Distance entre terrain des essences - la courneuve et arena champs de mars : 15638.75 mètres
Distance entre terrain des essences - la courneuve et stade tour eiffel : 15825.71 mètres
Distance entre terrain des essences - la courneuve et stade bmx de saint-quentin-en-yvelines : 45115.37 mètres
Distance entre terrain des essences - la courneuve et arena la chapelle : 7209.139 mètres
Distance entre terrain des essences - la courneuve et stade pierre de coubertin : 20747.46 mètres
Distance entre terrain des essences - la courneuve et centre aquatique : 6325.288 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 1 (porte de versailles) : 18647.47 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 4 (porte de versailles) : 18379.7 mètres
Distance entre terrain des essences - la courneuve et hôtel de ville de paris : 11634.91 mètres
Distance entre terrain des essences - la courneuve et la défense arena : 20609.08 mètres
Distance entre terrain des essences - la courneuve et stade nautique : 26997.17 mètres
Distance entre terrain des essences - la courneuve et golf national : 42805.96 mètres
Distance entre terrain des essences - la courneuve et vélodrome national de saint-quentin-en-yvelines : 45055.79 mètres
Distance entre terrain des essences - la courneuve et stade roland garros : 21105.54 mètres
Distance entre terrain des essences - la courneuve et clichy-sous-bois : 15821.18 mètres
Distance entre colline d'elancourt et grand palais : 39330.06 mètres
Distance entre colline d'elancourt et invalides : 39328.98 mètres
Distance entre colline d'elancourt et site d'escalade du bourget : 53049.92 mètres
Distance entre colline d'elancourt et pont d'iéna : 36813.56 mètres
Distance entre colline d'elancourt et arena bercy : 46064.78 mètres
Distance entre colline d'elancourt et arena paris nord : 64674.87 mètres
Distance entre colline d'elancourt et arena paris sud 6 (porte de versailles) : 36250.93 mètres
Distance entre colline d'elancourt et stade de la concorde : 40275.29 mètres
Distance entre colline d'elancourt et stade yves du manoir : 35184.12 mètres
Distance entre colline d'elancourt et arena champs de mars : 37757.95 mètres
Distance entre colline d'elancourt et stade tour eiffel : 37346.02 mètres
Distance entre colline d'elancourt et stade bmx de saint-quentin-en-yvelines : 7454.627 mètres
Distance entre colline d'elancourt et arena la chapelle : 45577.4 mètres
Distance entre colline d'elancourt et stade pierre de coubertin : 32657.84 mètres
Distance entre colline d'elancourt et centre aquatique : 45712.81 mètres
Distance entre colline d'elancourt et arena paris sud 1 (porte de versailles) : 35553.01 mètres
Distance entre colline d'elancourt et arena paris sud 4 (porte de versailles) : 36077.34 mètres
Distance entre colline d'elancourt et hôtel de ville de paris : 43384.81 mètres
Distance entre colline d'elancourt et la défense arena : 31515.36 mètres
Distance entre colline d'elancourt et stade nautique : 74882.55 mètres
Distance entre colline d'elancourt et golf national : 12723.12 mètres
Distance entre colline d'elancourt et vélodrome national de saint-quentin-en-yvelines : 7481.905 mètres
Distance entre colline d'elancourt et stade roland garros : 31608.88 mètres
Distance entre colline d'elancourt et clichy-sous-bois : 65849.1 mètres
Distance entre grand palais et invalides : 427.428 mètres
Nouvelle distance trouvée : grand palais et invalides avec distance : 427.428 mètres
Distance entre grand palais et site d'escalade du bourget : 14398.76 mètres
Distance entre grand palais et pont d'iéna : 2578.979 mètres
Distance entre grand palais et arena bercy : 7963.004 mètres
Distance entre grand palais et arena paris nord : 25825.03 mètres
Distance entre grand palais et arena paris sud 6 (porte de versailles) : 4712.212 mètres
Distance entre grand palais et stade de la concorde : 980.7896 mètres
Distance entre grand palais et stade yves du manoir : 10025.88 mètres
Distance entre grand palais et arena champs de mars : 1849.32 mètres
Distance entre grand palais et stade tour eiffel : 2064.311 mètres
Distance entre grand palais et stade bmx de saint-quentin-en-yvelines : 32128.35 mètres
Distance entre grand palais et arena la chapelle : 6638.76 mètres
Distance entre grand palais et stade pierre de coubertin : 7024.637 mètres
Distance entre grand palais et centre aquatique : 7989.103 mètres
Distance entre grand palais et arena paris sud 1 (porte de versailles) : 4918.34 mètres
Distance entre grand palais et arena paris sud 4 (porte de versailles) : 4751.984 mètres
Distance entre grand palais et hôtel de ville de paris : 4460.968 mètres
Distance entre grand palais et la défense arena : 9777.461 mètres
Distance entre grand palais et stade nautique : 36066.44 mètres
Distance entre grand palais et golf national : 29268.41 mètres
Distance entre grand palais et vélodrome national de saint-quentin-en-yvelines : 32077.74 mètres
Distance entre grand palais et stade roland garros : 7733.461 mètres
Distance entre grand palais et clichy-sous-bois : 26527.01 mètres
Distance entre invalides et site d'escalade du bourget : 14557.86 mètres
Distance entre invalides et pont d'iéna : 2519.929 mètres
Distance entre invalides et arena bercy : 7727.262 mètres
Distance entre invalides et arena paris nord : 25936.7 mètres
Distance entre invalides et arena paris sud 6 (porte de versailles) : 4409.24 mètres
Distance entre invalides et stade de la concorde : 961.6114 mètres
Distance entre invalides et stade yves du manoir : 10391.84 mètres
Distance entre invalides et arena champs de mars : 1666.21 mètres
Distance entre invalides et stade tour eiffel : 1988.892 mètres
Distance entre invalides et stade bmx de saint-quentin-en-yvelines : 32104.64 mètres
Distance entre invalides et arena la chapelle : 6809.104 mètres
Distance entre invalides et stade pierre de coubertin : 6911.713 mètres
Distance entre invalides et centre aquatique : 8274.713 mètres
Distance entre invalides et arena paris sud 1 (porte de versailles) : 4667.773 mètres
Distance entre invalides et arena paris sud 4 (porte de versailles) : 4461.792 mètres
Distance entre invalides et hôtel de ville de paris : 4294.278 mètres
Distance entre invalides et la défense arena : 10010.3 mètres
Distance entre invalides et stade nautique : 35973.12 mètres
Distance entre invalides et golf national : 29170.6 mètres
Distance entre invalides et vélodrome national de saint-quentin-en-yvelines : 32055.06 mètres
Distance entre invalides et stade roland garros : 7720.278 mètres
Distance entre invalides et clichy-sous-bois : 26520.3 mètres
Distance entre site d'escalade du bourget et pont d'iéna : 16954.31 mètres
Distance entre site d'escalade du bourget et arena bercy : 11914.04 mètres
Distance entre site d'escalade du bourget et arena paris nord : 11625.97 mètres
Distance entre site d'escalade du bourget et arena paris sud 6 (porte de versailles) : 18749.97 mètres
Distance entre site d'escalade du bourget et stade de la concorde : 13620.42 mètres
Distance entre site d'escalade du bourget et stade yves du manoir : 19007.54 mètres
Distance entre site d'escalade du bourget et arena champs de mars : 16220.87 mètres
Distance entre site d'escalade du bourget et stade tour eiffel : 16456.19 mètres
Distance entre site d'escalade du bourget et stade bmx de saint-quentin-en-yvelines : 46064.28 mètres
Distance entre site d'escalade du bourget et arena la chapelle : 7761.018 mètres
Distance entre site d'escalade du bourget et stade pierre de coubertin : 21411.54 mètres
Distance entre site d'escalade du bourget et centre aquatique : 7388.643 mètres
Distance entre site d'escalade du bourget et arena paris sud 1 (porte de versailles) : 19158.75 mètres
Distance entre site d'escalade du bourget et arena paris sud 4 (porte de versailles) : 18849.17 mètres
Distance entre site d'escalade du bourget et hôtel de ville de paris : 11786.15 mètres
Distance entre site d'escalade du bourget et la défense arena : 21731.54 mètres
Distance entre site d'escalade du bourget et stade nautique : 25439.3 mètres
Distance entre site d'escalade du bourget et golf national : 43586.04 mètres
Distance entre site d'escalade du bourget et vélodrome national de saint-quentin-en-yvelines : 46006.67 mètres
Distance entre site d'escalade du bourget et stade roland garros : 21892.32 mètres
Distance entre site d'escalade du bourget et clichy-sous-bois : 14313.45 mètres
Distance entre pont d'iéna et arena bercy : 9891.422 mètres
Distance entre pont d'iéna et arena paris nord : 28402.56 mètres
Distance entre pont d'iéna et arena paris sud 6 (porte de versailles) : 2963.77 mètres
Distance entre pont d'iéna et stade de la concorde : 3476.289 mètres
Distance entre pont d'iéna et stade yves du manoir : 9501.775 mètres
Distance entre pont d'iéna et arena champs de mars : 1021.525 mètres
Distance entre pont d'iéna et stade tour eiffel : 532.4663 mètres
Distance entre pont d'iéna et stade bmx de saint-quentin-en-yvelines : 29584.77 mètres
Distance entre pont d'iéna et arena la chapelle : 9194.18 mètres
Distance entre pont d'iéna et stade pierre de coubertin : 4457.281 mètres
Distance entre pont d'iéna et centre aquatique : 10335.35 mètres
Distance entre pont d'iéna et arena paris sud 1 (porte de versailles) : 2810.3 mètres
Distance entre pont d'iéna et arena paris sud 4 (porte de versailles) : 2906.488 mètres
Distance entre pont d'iéna et hôtel de ville de paris : 6681.168 mètres
Distance entre pont d'iéna et la défense arena : 8146.46 mètres
Distance entre pont d'iéna et stade nautique : 38408.06 mètres
Distance entre pont d'iéna et golf national : 26689.83 mètres
Distance entre pont d'iéna et vélodrome national de saint-quentin-en-yvelines : 29535.23 mètres
Distance entre pont d'iéna et stade roland garros : 5205.364 mètres
Distance entre pont d'iéna et clichy-sous-bois : 29035.72 mètres
Distance entre arena bercy et arena paris nord : 21516.85 mètres
Distance entre arena bercy et arena paris sud 6 (porte de versailles) : 9816.295 mètres
Distance entre arena bercy et stade de la concorde : 7046.447 mètres
Distance entre arena bercy et stade yves du manoir : 17616.92 mètres
Distance entre arena bercy et arena champs de mars : 8869.957 mètres
Distance entre arena bercy et stade tour eiffel : 9404.021 mètres
Distance entre arena bercy et stade bmx de saint-quentin-en-yvelines : 38691.77 mètres
Distance entre arena bercy et arena la chapelle : 7016.752 mètres
Distance entre arena bercy et stade pierre de coubertin : 13490.06 mètres
Distance entre arena bercy et centre aquatique : 9773.131 mètres
Distance entre arena bercy et arena paris sud 1 (porte de versailles) : 10530.69 mètres
Distance entre arena bercy et arena paris sud 4 (porte de versailles) : 9992.586 mètres
Distance entre arena bercy et hôtel de ville de paris : 3631.786 mètres
Distance entre arena bercy et la défense arena : 17735.22 mètres
Distance entre arena bercy et stade nautique : 28826.38 mètres
Distance entre arena bercy et golf national : 35064.48 mètres
Distance entre arena bercy et vélodrome national de saint-quentin-en-yvelines : 38651.32 mètres
Distance entre arena bercy et stade roland garros : 14836.32 mètres
Distance entre arena bercy et clichy-sous-bois : 20357.07 mètres
Distance entre arena paris nord et arena paris sud 6 (porte de versailles) : 29913.68 mètres
Distance entre arena paris nord et stade de la concorde : 24979.54 mètres
Distance entre arena paris nord et stade yves du manoir : 30319.07 mètres
Distance entre arena paris nord et arena champs de mars : 27600.34 mètres
Distance entre arena paris nord et stade tour eiffel : 27888.78 mètres
Distance entre arena paris nord et stade bmx de saint-quentin-en-yvelines : 57683.56 mètres
Distance entre arena paris nord et arena la chapelle : 19254.99 mètres
Distance entre arena paris nord et stade pierre de coubertin : 32845.14 mètres
Distance entre arena paris nord et centre aquatique : 18979.71 mètres
Distance entre arena paris nord et arena paris sud 1 (porte de versailles) : 30406.15 mètres
Distance entre arena paris nord et arena paris sud 4 (porte de versailles) : 30034.73 mètres
Distance entre arena paris nord et hôtel de ville de paris : 22601.59 mètres
Distance entre arena paris nord et la défense arena : 33304.5 mètres
Distance entre arena paris nord et stade nautique : 17814.32 mètres
Distance entre arena paris nord et golf national : 55091.12 mètres
Distance entre arena paris nord et vélodrome national de saint-quentin-en-yvelines : 57626.49 mètres
Distance entre arena paris nord et stade roland garros : 33442.15 mètres
Distance entre arena paris nord et clichy-sous-bois : 7341.222 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade de la concorde : 5241.777 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade yves du manoir : 12149.36 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena champs de mars : 2971.343 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade tour eiffel : 3127.157 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade bmx de saint-quentin-en-yvelines : 28889.3 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena la chapelle : 11085.62 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade pierre de coubertin : 3770.201 mètres
Distance entre arena paris sud 6 (porte de versailles) et centre aquatique : 12683.94 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena paris sud 1 (porte de versailles) : 788.7158 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena paris sud 4 (porte de versailles) : 195.7977 mètres
Nouvelle distance trouvée : arena paris sud 6 (porte de versailles) et arena paris sud 4 (porte de versailles) avec distance : 195.7977 mètres
Distance entre arena paris sud 6 (porte de versailles) et hôtel de ville de paris : 7398.72 mètres
Distance entre arena paris sud 6 (porte de versailles) et la défense arena : 10008.33 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade nautique : 38642.2 mètres
Distance entre arena paris sud 6 (porte de versailles) et golf national : 25465.16 mètres
Distance entre arena paris sud 6 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28847.6 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade roland garros : 5410.831 mètres
Distance entre arena paris sud 6 (porte de versailles) et clichy-sous-bois : 29866.16 mètres
Distance entre stade de la concorde et stade yves du manoir : 10763.37 mètres
Distance entre stade de la concorde et arena champs de mars : 2620.806 mètres
Distance entre stade de la concorde et stade tour eiffel : 2946.9 mètres
Distance entre stade de la concorde et stade bmx de saint-quentin-en-yvelines : 33058.49 mètres
Distance entre stade de la concorde et arena la chapelle : 5885.3 mètres
Distance entre stade de la concorde et stade pierre de coubertin : 7871.815 mètres
Distance entre stade de la concorde et centre aquatique : 7485.05 mètres
Distance entre stade de la concorde et arena paris sud 1 (porte de versailles) : 5562.295 mètres
Distance entre stade de la concorde et arena paris sud 4 (porte de versailles) : 5312.2 mètres
Distance entre stade de la concorde et hôtel de ville de paris : 3500.37 mètres
Distance entre stade de la concorde et la défense arena : 10720.35 mètres
Distance entre stade de la concorde et stade nautique : 35086.44 mètres
Distance entre stade de la concorde et golf national : 30131.23 mètres
Distance entre stade de la concorde et vélodrome national de saint-quentin-en-yvelines : 33008.62 mètres
Distance entre stade de la concorde et stade roland garros : 8668.867 mètres
Distance entre stade de la concorde et clichy-sous-bois : 25575.8 mètres
Distance entre stade yves du manoir et arena champs de mars : 10188.13 mètres
Distance entre stade yves du manoir et stade tour eiffel : 9674.774 mètres
Distance entre stade yves du manoir et stade bmx de saint-quentin-en-yvelines : 28784.98 mètres
Distance entre stade yves du manoir et arena la chapelle : 12943.9 mètres
Distance entre stade yves du manoir et stade pierre de coubertin : 10679.74 mètres
Distance entre stade yves du manoir et centre aquatique : 11794.35 mètres
Distance entre stade yves du manoir et arena paris sud 1 (porte de versailles) : 11634.33 mètres
Distance entre stade yves du manoir et arena paris sud 4 (porte de versailles) : 12018.71 mètres
Distance entre stade yves du manoir et hôtel de ville de paris : 13987.19 mètres
Distance entre stade yves du manoir et la défense arena : 4512.378 mètres
Distance entre stade yves du manoir et stade nautique : 43701.24 mètres
Distance entre stade yves du manoir et golf national : 27836.06 mètres
Distance entre stade yves du manoir et vélodrome national de saint-quentin-en-yvelines : 28713.33 mètres
Distance entre stade yves du manoir et stade roland garros : 9306.441 mètres
Distance entre stade yves du manoir et clichy-sous-bois : 33085.35 mètres
Distance entre arena champs de mars et stade tour eiffel : 567.5872 mètres
Distance entre arena champs de mars et stade bmx de saint-quentin-en-yvelines : 30507.17 mètres
Distance entre arena champs de mars et arena la chapelle : 8467.326 mètres
Distance entre arena champs de mars et stade pierre de coubertin : 5254.769 mètres
Distance entre arena champs de mars et centre aquatique : 9818.745 mètres
Distance entre arena champs de mars et arena paris sud 1 (porte de versailles) : 3087.526 mètres
Distance entre arena champs de mars et arena paris sud 4 (porte de versailles) : 2981.165 mètres
Distance entre arena champs de mars et hôtel de ville de paris : 5683.388 mètres
Distance entre arena champs de mars et la défense arena : 9103.359 mètres
Distance entre arena champs de mars et stade nautique : 37408.79 mètres
Distance entre arena champs de mars et golf national : 27514.28 mètres
Distance entre arena champs de mars et vélodrome national de saint-quentin-en-yvelines : 30458.76 mètres
Distance entre arena champs de mars et stade roland garros : 6165.247 mètres
Distance entre arena champs de mars et clichy-sous-bois : 28098.06 mètres
Distance entre stade tour eiffel et stade bmx de saint-quentin-en-yvelines : 30116.34 mètres
Distance entre stade tour eiffel et arena la chapelle : 8695.175 mètres
Distance entre stade tour eiffel et stade pierre de coubertin : 4960.72 mètres
Distance entre stade tour eiffel et centre aquatique : 9901.803 mètres
Distance entre stade tour eiffel et arena paris sud 1 (porte de versailles) : 3099.422 mètres
Distance entre stade tour eiffel et arena paris sud 4 (porte de versailles) : 3101.604 mètres
Distance entre stade tour eiffel et hôtel de ville de paris : 6159.559 mètres
Distance entre stade tour eiffel et la défense arena : 8536.047 mètres
Distance entre stade tour eiffel et stade nautique : 37884.99 mètres
Distance entre stade tour eiffel et golf national : 27206.09 mètres
Distance entre stade tour eiffel et vélodrome national de saint-quentin-en-yvelines : 30066.88 mètres
Distance entre stade tour eiffel et stade roland garros : 5737.797 mètres
Distance entre stade tour eiffel et clichy-sous-bois : 28503.27 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena la chapelle : 38489.51 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade pierre de coubertin : 25348.99 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et centre aquatique : 38791.12 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena paris sud 1 (porte de versailles) : 28205.86 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena paris sud 4 (porte de versailles) : 28719.15 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et hôtel de ville de paris : 36092.63 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et la défense arena : 24829.22 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade nautique : 67491.12 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et golf national : 6098.004 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et vélodrome national de saint-quentin-en-yvelines : 91.69166 mètres
Nouvelle distance trouvée : stade bmx de saint-quentin-en-yvelines et vélodrome national de saint-quentin-en-yvelines avec distance : 91.69166 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade roland garros : 24394.96 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et clichy-sous-bois : 58601.78 mètres
Distance entre arena la chapelle et stade pierre de coubertin : 13651.43 mètres
Distance entre arena la chapelle et centre aquatique : 2756.517 mètres
Distance entre arena la chapelle et arena paris sud 1 (porte de versailles) : 11445.37 mètres
Distance entre arena la chapelle et arena paris sud 4 (porte de versailles) : 11170.78 mètres
Distance entre arena la chapelle et hôtel de ville de paris : 4879.972 mètres
Distance entre arena la chapelle et la défense arena : 14710.67 mètres
Distance entre arena la chapelle et stade nautique : 30844.63 mètres
Distance entre arena la chapelle et golf national : 35852.22 mètres
Distance entre arena la chapelle et vélodrome national de saint-quentin-en-yvelines : 38434.83 mètres
Distance entre arena la chapelle et stade roland garros : 14187.33 mètres
Distance entre arena la chapelle et clichy-sous-bois : 20589.85 mètres
Distance entre stade pierre de coubertin et centre aquatique : 14692.67 mètres
Distance entre stade pierre de coubertin et arena paris sud 1 (porte de versailles) : 2998.992 mètres
Distance entre stade pierre de coubertin et arena paris sud 4 (porte de versailles) : 3578.044 mètres
Distance entre stade pierre de coubertin et hôtel de ville de paris : 10744.47 mètres
Distance entre stade pierre de coubertin et la défense arena : 7400.604 mètres
Distance entre stade pierre de coubertin et stade nautique : 42298.61 mètres
Distance entre stade pierre de coubertin et golf national : 22259.76 mètres
Distance entre stade pierre de coubertin et vélodrome national de saint-quentin-en-yvelines : 25303.44 mètres
Distance entre stade pierre de coubertin et stade roland garros : 1890.523 mètres
Distance entre stade pierre de coubertin et clichy-sous-bois : 33267.48 mètres
Distance entre centre aquatique et arena paris sud 1 (porte de versailles) : 12903.64 mètres
Distance entre centre aquatique et arena paris sud 4 (porte de versailles) : 12734.24 mètres
Distance entre centre aquatique et hôtel de ville de paris : 7421.643 mètres
Distance entre centre aquatique et la défense arena : 14343.1 mètres
Distance entre centre aquatique et stade nautique : 31996.71 mètres
Distance entre centre aquatique et golf national : 36558.83 mètres
Distance entre centre aquatique et vélodrome national de saint-quentin-en-yvelines : 38731.36 mètres
Distance entre centre aquatique et stade roland garros : 14890.71 mètres
Distance entre centre aquatique et clichy-sous-bois : 21291.13 mètres
Distance entre arena paris sud 1 (porte de versailles) et arena paris sud 4 (porte de versailles) : 592.9181 mètres
Distance entre arena paris sud 1 (porte de versailles) et hôtel de ville de paris : 7981.963 mètres
Distance entre arena paris sud 1 (porte de versailles) et la défense arena : 9312.84 mètres
Distance entre arena paris sud 1 (porte de versailles) et stade nautique : 39355.28 mètres
Distance entre arena paris sud 1 (porte de versailles) et golf national : 24868.19 mètres
Distance entre arena paris sud 1 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28163.04 mètres
Distance entre arena paris sud 1 (porte de versailles) et stade roland garros : 4622.308 mètres
Distance entre arena paris sud 1 (porte de versailles) et clichy-sous-bois : 30492.85 mètres
Distance entre arena paris sud 4 (porte de versailles) et hôtel de ville de paris : 7539.999 mètres
Distance entre arena paris sud 4 (porte de versailles) et la défense arena : 9834.345 mètres
Distance entre arena paris sud 4 (porte de versailles) et stade nautique : 38818.94 mètres
Distance entre arena paris sud 4 (porte de versailles) et golf national : 25316.01 mètres
Distance entre arena paris sud 4 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28677.18 mètres
Distance entre arena paris sud 4 (porte de versailles) et stade roland garros : 5215.075 mètres
Distance entre arena paris sud 4 (porte de versailles) et clichy-sous-bois : 30021 mètres
Distance entre hôtel de ville de paris et la défense arena : 14218.99 mètres
Distance entre hôtel de ville de paris et stade nautique : 31727.11 mètres
Distance entre hôtel de ville de paris et golf national : 32849.18 mètres
Distance entre hôtel de ville de paris et vélodrome national de saint-quentin-en-yvelines : 36046.69 mètres
Distance entre hôtel de ville de paris et stade roland garros : 11837.93 mètres
Distance entre hôtel de ville de paris et clichy-sous-bois : 22530.34 mètres
Distance entre la défense arena et stade nautique : 45422.07 mètres
Distance entre la défense arena et golf national : 23490.01 mètres
Distance entre la défense arena et vélodrome national de saint-quentin-en-yvelines : 24762.46 mètres
Distance entre la défense arena et stade roland garros : 5657.121 mètres
Distance entre la défense arena et clichy-sous-bois : 35295.47 mètres
Distance entre stade nautique et golf national : 63604.35 mètres
Distance entre stade nautique et vélodrome national de saint-quentin-en-yvelines : 67452.65 mètres
Distance entre stade nautique et stade roland garros : 43543.37 mètres
Distance entre stade nautique et clichy-sous-bois : 11400.29 mètres
Distance entre golf national et vélodrome national de saint-quentin-en-yvelines : 6135.202 mètres
Distance entre golf national et stade roland garros : 21703.18 mètres
Distance entre golf national et clichy-sous-bois : 55319.43 mètres
Distance entre vélodrome national de saint-quentin-en-yvelines et stade roland garros : 24344.29 mètres
Distance entre vélodrome national de saint-quentin-en-yvelines et clichy-sous-bois : 58554.14 mètres
Distance entre stade roland garros et clichy-sous-bois : 34240.23 mètres</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#code final pour avoir la distance la plus courte</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(site1) <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="fu">is.null</span>(site2)) {</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Les deux sites les plus proches en distance sont :"</span>, site1, <span class="st">"et"</span>, site2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Les deux sites les plus proches en distance sont : stade bmx de saint-quentin-en-yvelines et vélodrome national de saint-quentin-en-yvelines </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(distance_min)) {</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"La distance entre ces deux sites va être de :"</span>, distance_min, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La distance entre ces deux sites va être de : 91.69166 mètres</code></pre>
</div>
</div>
<p><em>Les deux sites les plus proches en distance sont : stade bmx de saint-quentin-en-yvelines et vélodrome national de saint-quentin-en-yvelines et la distance entre ces deux sites va être de : 91.69166 mètres</em></p>
<p><strong>Question 10</strong> : Quels sont les deux sites les plus éloignés ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>site3 <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>site4 <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>distance_max <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (x <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">nrow</span>(coordonnees) <span class="sc">-</span> <span class="dv">1</span>)) {</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (y <span class="cf">in</span> (x <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span><span class="fu">nrow</span>(coordonnees)) {</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    nom_site_x <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">trimws</span>(noms_sites[x]))</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    nom_site_y <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">trimws</span>(noms_sites[y]))</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Calculons la distance entre les sites que l'on va nommé ici x et y différent de i et j car ici on veut le max</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    distance <span class="ot">&lt;-</span> <span class="fu">distHaversine</span>(coordonnees[<span class="fu">c</span>(x, y), , <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Distance entre"</span>, nom_site_x, <span class="st">"et"</span>, nom_site_y, <span class="st">":"</span>, distance, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#code pour connaitre la distance la plus éloignée</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (distance <span class="sc">&gt;</span> distance_max) {</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>      distance_max <span class="ot">&lt;-</span> distance</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>      site3 <span class="ot">&lt;-</span> nom_site_x</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>      site4 <span class="ot">&lt;-</span> nom_site_y</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"Nouvelle paire trouvée :"</span>, site3, <span class="st">"et"</span>, site4, <span class="st">"avec distance :"</span>, distance_max, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Distance entre parc des princes et stade de france : 15056.74 mètres
Nouvelle paire trouvée : parc des princes et stade de france avec distance : 15056.74 mètres
Distance entre parc des princes et village olympique : 12805.62 mètres
Distance entre parc des princes et château de versailles : 19257.08 mètres
Nouvelle paire trouvée : parc des princes et château de versailles avec distance : 19257.08 mètres
Distance entre parc des princes et village des médias : 22271.85 mètres
Nouvelle paire trouvée : parc des princes et village des médias avec distance : 22271.85 mètres
Distance entre parc des princes et terrain des essences - la courneuve : 20748.36 mètres
Distance entre parc des princes et colline d'elancourt : 32305.28 mètres
Nouvelle paire trouvée : parc des princes et colline d'elancourt avec distance : 32305.28 mètres
Distance entre parc des princes et grand palais : 7154.178 mètres
Distance entre parc des princes et invalides : 7089.976 mètres
Distance entre parc des princes et site d'escalade du bourget : 21469.18 mètres
Distance entre parc des princes et pont d'iéna : 4578.563 mètres
Distance entre parc des princes et arena bercy : 13964.85 mètres
Distance entre parc des princes et arena paris nord : 32963.04 mètres
Nouvelle paire trouvée : parc des princes et arena paris nord avec distance : 32963.04 mètres
Distance entre parc des princes et arena paris sud 6 (porte de versailles) : 4393.84 mètres
Distance entre parc des princes et stade de la concorde : 8050.22 mètres
Distance entre parc des princes et stade yves du manoir : 9967.937 mètres
Distance entre parc des princes et arena champs de mars : 5470.767 mètres
Distance entre parc des princes et stade tour eiffel : 5104.351 mètres
Distance entre parc des princes et stade bmx de saint-quentin-en-yvelines : 25038.36 mètres
Distance entre parc des princes et arena la chapelle : 13723.99 mètres
Distance entre parc des princes et stade pierre de coubertin : 835.1916 mètres
Distance entre parc des princes et centre aquatique : 14612.97 mètres
Distance entre parc des princes et arena paris sud 1 (porte de versailles) : 3606.39 mètres
Distance entre parc des princes et arena paris sud 4 (porte de versailles) : 4198.314 mètres
Distance entre parc des princes et hôtel de ville de paris : 11082.65 mètres
Distance entre parc des princes et la défense arena : 6580.477 mètres
Distance entre parc des princes et stade nautique : 42731.87 mètres
Nouvelle paire trouvée : parc des princes et stade nautique avec distance : 42731.87 mètres
Distance entre parc des princes et golf national : 22129.94 mètres
Distance entre parc des princes et vélodrome national de saint-quentin-en-yvelines : 24990.38 mètres
Distance entre parc des princes et stade roland garros : 1075.47 mètres
Distance entre parc des princes et clichy-sous-bois : 33564 mètres
Distance entre stade de france et village olympique : 3055.102 mètres
Distance entre stade de france et château de versailles : 33226.67 mètres
Distance entre stade de france et village des médias : 7547.578 mètres
Distance entre stade de france et terrain des essences - la courneuve : 5838.553 mètres
Distance entre stade de france et colline d'elancourt : 46203.55 mètres
Nouvelle paire trouvée : stade de france et colline d'elancourt avec distance : 46203.55 mètres
Distance entre stade de france et grand palais : 8368.71 mètres
Distance entre stade de france et invalides : 8641.704 mètres
Distance entre stade de france et site d'escalade du bourget : 6894.111 mètres
Distance entre stade de france et pont d'iéna : 10747.83 mètres
Distance entre stade de france et arena bercy : 9759.047 mètres
Distance entre stade de france et arena paris nord : 18486.54 mètres
Distance entre stade de france et arena paris sud 6 (porte de versailles) : 13048.34 mètres
Distance entre stade de france et stade de la concorde : 7829.343 mètres
Distance entre stade de france et stade yves du manoir : 12270.26 mètres
Distance entre stade de france et arena champs de mars : 10206.54 mètres
Distance entre stade de france et stade tour eiffel : 10306.09 mètres
Distance entre stade de france et stade bmx de saint-quentin-en-yvelines : 39276.84 mètres
Distance entre stade de france et arena la chapelle : 2778.395 mètres
Distance entre stade de france et stade pierre de coubertin : 15123.54 mètres
Distance entre stade de france et centre aquatique : 494.5346 mètres
Distance entre stade de france et arena paris sud 1 (porte de versailles) : 13286.85 mètres
Distance entre stade de france et arena paris sud 4 (porte de versailles) : 13103.5 mètres
Distance entre stade de france et hôtel de ville de paris : 7569.808 mètres
Distance entre stade de france et la défense arena : 14837.62 mètres
Distance entre stade de france et stade nautique : 31546.91 mètres
Distance entre stade de france et golf national : 37025.23 mètres
Distance entre stade de france et vélodrome national de saint-quentin-en-yvelines : 39217.24 mètres
Distance entre stade de france et stade roland garros : 15348.53 mètres
Distance entre stade de france et clichy-sous-bois : 20815.62 mètres
Distance entre village olympique et château de versailles : 30416.63 mètres
Distance entre village olympique et village des médias : 10500.75 mètres
Distance entre village olympique et terrain des essences - la courneuve : 8728.774 mètres
Distance entre village olympique et colline d'elancourt : 43340.21 mètres
Distance entre village olympique et grand palais : 6891.563 mètres
Distance entre village olympique et invalides : 7260.763 mètres
Distance entre village olympique et site d'escalade du bourget : 9898.861 mètres
Distance entre village olympique et pont d'iéna : 8874.43 mètres
Distance entre village olympique et arena bercy : 10855.43 mètres
Distance entre village olympique et arena paris nord : 21426.96 mètres
Distance entre village olympique et arena paris sud 6 (porte de versailles) : 11543.92 mètres
Distance entre village olympique et stade de la concorde : 6689.15 mètres
Distance entre village olympique et stade yves du manoir : 9219.952 mètres
Distance entre village olympique et arena champs de mars : 8576.444 mètres
Distance entre village olympique et stade tour eiffel : 8522.563 mètres
Distance entre village olympique et stade bmx de saint-quentin-en-yvelines : 36494.17 mètres
Distance entre village olympique et arena la chapelle : 4305.937 mètres
Distance entre village olympique et stade pierre de coubertin : 12998.42 mètres
Distance entre village olympique et centre aquatique : 2574.906 mètres
Distance entre village olympique et arena paris sud 1 (porte de versailles) : 11619.06 mètres
Distance entre village olympique et arena paris sud 4 (porte de versailles) : 11557.56 mètres
Distance entre village olympique et hôtel de ville de paris : 7833.045 mètres
Distance entre village olympique et la défense arena : 11881.1 mètres
Distance entre village olympique et stade nautique : 34540.4 mètres
Distance entre village olympique et golf national : 34471.37 mètres
Distance entre village olympique et vélodrome national de saint-quentin-en-yvelines : 36432.29 mètres
Distance entre village olympique et stade roland garros : 12948.41 mètres
Distance entre village olympique et clichy-sous-bois : 23865.88 mètres
Distance entre château de versailles et village des médias : 40755.46 mètres
Distance entre château de versailles et terrain des essences - la courneuve : 39064.07 mètres
Distance entre château de versailles et colline d'elancourt : 13072.8 mètres
Distance entre château de versailles et grand palais : 26258.12 mètres
Distance entre château de versailles et invalides : 26260.18 mètres
Distance entre château de versailles et site d'escalade du bourget : 40041.69 mètres
Distance entre château de versailles et pont d'iéna : 23746.69 mètres
Distance entre château de versailles et arena bercy : 33100.56 mètres
Distance entre château de versailles et arena paris nord : 51666.84 mètres
Nouvelle paire trouvée : château de versailles et arena paris nord avec distance : 51666.84 mètres
Distance entre château de versailles et arena paris sud 6 (porte de versailles) : 23288.04 mètres
Distance entre château de versailles et stade de la concorde : 27204.95 mètres
Distance entre château de versailles et stade yves du manoir : 22683.74 mètres
Distance entre château de versailles et arena champs de mars : 24697.14 mètres
Distance entre château de versailles et stade tour eiffel : 24279.13 mètres
Distance entre château de versailles et stade bmx de saint-quentin-en-yvelines : 6113.76 mètres
Distance entre château de versailles et arena la chapelle : 32522.1 mètres
Distance entre château de versailles et stade pierre de coubertin : 19639.37 mètres
Distance entre château de versailles et centre aquatique : 32738.84 mètres
Distance entre château de versailles et arena paris sud 1 (porte de versailles) : 22570.58 mètres
Distance entre château de versailles et arena paris sud 4 (porte de versailles) : 23109.51 mètres
Distance entre château de versailles et hôtel de ville de paris : 30339.66 mètres
Distance entre château de versailles et la défense arena : 18717.88 mètres
Distance entre château de versailles et stade nautique : 61925.84 mètres
Nouvelle paire trouvée : château de versailles et stade nautique avec distance : 61925.84 mètres
Distance entre château de versailles et golf national : 7155.132 mètres
Distance entre château de versailles et vélodrome national de saint-quentin-en-yvelines : 6045.72 mètres
Distance entre château de versailles et stade roland garros : 18541.33 mètres
Distance entre château de versailles et clichy-sous-bois : 52780.3 mètres
Distance entre village des médias et terrain des essences - la courneuve : 1832.738 mètres
Distance entre village des médias et colline d'elancourt : 53746.49 mètres
Distance entre village des médias et grand palais : 15228.01 mètres
Distance entre village des médias et invalides : 15396.94 mètres
Distance entre village des médias et site d'escalade du bourget : 912.7678 mètres
Distance entre village des médias et pont d'iéna : 17774.34 mètres
Distance entre village des médias et arena bercy : 12818.29 mètres
Distance entre village des médias et arena paris nord : 10939.62 mètres
Distance entre village des médias et arena paris sud 6 (porte de versailles) : 19614.57 mètres
Distance entre village des médias et stade de la concorde : 14464.99 mètres
Distance entre village des médias et stade yves du manoir : 19523.96 mètres
Distance entre village des médias et arena champs de mars : 17057.13 mètres
Distance entre village des médias et stade tour eiffel : 17280.72 mètres
Distance entre village des médias et stade bmx de saint-quentin-en-yvelines : 46791.15 mètres
Distance entre village des médias et arena la chapelle : 8590.226 mètres
Distance entre village des médias et stade pierre de coubertin : 22230.22 mètres
Distance entre village des médias et centre aquatique : 8040.421 mètres
Distance entre village des médias et arena paris sud 1 (porte de versailles) : 20012.59 mètres
Distance entre village des médias et arena paris sud 4 (porte de versailles) : 19711.16 mètres
Distance entre village des médias et hôtel de ville de paris : 12687.31 mètres
Distance entre village des médias et la défense arena : 22369.47 mètres
Distance entre village des médias et stade nautique : 25263.98 mètres
Distance entre village des médias et golf national : 44375.48 mètres
Distance entre village des médias et vélodrome national de saint-quentin-en-yvelines : 46732.7 mètres
Distance entre village des médias et stade roland garros : 22674.64 mètres
Distance entre village des médias et clichy-sous-bois : 14034.31 mètres
Distance entre terrain des essences - la courneuve et colline d'elancourt : 52032.17 mètres
Distance entre terrain des essences - la courneuve et grand palais : 13794.37 mètres
Distance entre terrain des essences - la courneuve et invalides : 13993.97 mètres
Distance entre terrain des essences - la courneuve et site d'escalade du bourget : 1592.056 mètres
Distance entre terrain des essences - la courneuve et pont d'iéna : 16305.12 mètres
Distance entre terrain des essences - la courneuve et arena bercy : 12245.61 mètres
Distance entre terrain des essences - la courneuve et arena paris nord : 12699.39 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 6 (porte de versailles) : 18294.68 mètres
Distance entre terrain des essences - la courneuve et stade de la concorde : 13085.19 mètres
Distance entre terrain des essences - la courneuve et stade yves du manoir : 17701.84 mètres
Distance entre terrain des essences - la courneuve et arena champs de mars : 15638.75 mètres
Distance entre terrain des essences - la courneuve et stade tour eiffel : 15825.71 mètres
Distance entre terrain des essences - la courneuve et stade bmx de saint-quentin-en-yvelines : 45115.37 mètres
Distance entre terrain des essences - la courneuve et arena la chapelle : 7209.139 mètres
Distance entre terrain des essences - la courneuve et stade pierre de coubertin : 20747.46 mètres
Distance entre terrain des essences - la courneuve et centre aquatique : 6325.288 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 1 (porte de versailles) : 18647.47 mètres
Distance entre terrain des essences - la courneuve et arena paris sud 4 (porte de versailles) : 18379.7 mètres
Distance entre terrain des essences - la courneuve et hôtel de ville de paris : 11634.91 mètres
Distance entre terrain des essences - la courneuve et la défense arena : 20609.08 mètres
Distance entre terrain des essences - la courneuve et stade nautique : 26997.17 mètres
Distance entre terrain des essences - la courneuve et golf national : 42805.96 mètres
Distance entre terrain des essences - la courneuve et vélodrome national de saint-quentin-en-yvelines : 45055.79 mètres
Distance entre terrain des essences - la courneuve et stade roland garros : 21105.54 mètres
Distance entre terrain des essences - la courneuve et clichy-sous-bois : 15821.18 mètres
Distance entre colline d'elancourt et grand palais : 39330.06 mètres
Distance entre colline d'elancourt et invalides : 39328.98 mètres
Distance entre colline d'elancourt et site d'escalade du bourget : 53049.92 mètres
Distance entre colline d'elancourt et pont d'iéna : 36813.56 mètres
Distance entre colline d'elancourt et arena bercy : 46064.78 mètres
Distance entre colline d'elancourt et arena paris nord : 64674.87 mètres
Nouvelle paire trouvée : colline d'elancourt et arena paris nord avec distance : 64674.87 mètres
Distance entre colline d'elancourt et arena paris sud 6 (porte de versailles) : 36250.93 mètres
Distance entre colline d'elancourt et stade de la concorde : 40275.29 mètres
Distance entre colline d'elancourt et stade yves du manoir : 35184.12 mètres
Distance entre colline d'elancourt et arena champs de mars : 37757.95 mètres
Distance entre colline d'elancourt et stade tour eiffel : 37346.02 mètres
Distance entre colline d'elancourt et stade bmx de saint-quentin-en-yvelines : 7454.627 mètres
Distance entre colline d'elancourt et arena la chapelle : 45577.4 mètres
Distance entre colline d'elancourt et stade pierre de coubertin : 32657.84 mètres
Distance entre colline d'elancourt et centre aquatique : 45712.81 mètres
Distance entre colline d'elancourt et arena paris sud 1 (porte de versailles) : 35553.01 mètres
Distance entre colline d'elancourt et arena paris sud 4 (porte de versailles) : 36077.34 mètres
Distance entre colline d'elancourt et hôtel de ville de paris : 43384.81 mètres
Distance entre colline d'elancourt et la défense arena : 31515.36 mètres
Distance entre colline d'elancourt et stade nautique : 74882.55 mètres
Nouvelle paire trouvée : colline d'elancourt et stade nautique avec distance : 74882.55 mètres
Distance entre colline d'elancourt et golf national : 12723.12 mètres
Distance entre colline d'elancourt et vélodrome national de saint-quentin-en-yvelines : 7481.905 mètres
Distance entre colline d'elancourt et stade roland garros : 31608.88 mètres
Distance entre colline d'elancourt et clichy-sous-bois : 65849.1 mètres
Distance entre grand palais et invalides : 427.428 mètres
Distance entre grand palais et site d'escalade du bourget : 14398.76 mètres
Distance entre grand palais et pont d'iéna : 2578.979 mètres
Distance entre grand palais et arena bercy : 7963.004 mètres
Distance entre grand palais et arena paris nord : 25825.03 mètres
Distance entre grand palais et arena paris sud 6 (porte de versailles) : 4712.212 mètres
Distance entre grand palais et stade de la concorde : 980.7896 mètres
Distance entre grand palais et stade yves du manoir : 10025.88 mètres
Distance entre grand palais et arena champs de mars : 1849.32 mètres
Distance entre grand palais et stade tour eiffel : 2064.311 mètres
Distance entre grand palais et stade bmx de saint-quentin-en-yvelines : 32128.35 mètres
Distance entre grand palais et arena la chapelle : 6638.76 mètres
Distance entre grand palais et stade pierre de coubertin : 7024.637 mètres
Distance entre grand palais et centre aquatique : 7989.103 mètres
Distance entre grand palais et arena paris sud 1 (porte de versailles) : 4918.34 mètres
Distance entre grand palais et arena paris sud 4 (porte de versailles) : 4751.984 mètres
Distance entre grand palais et hôtel de ville de paris : 4460.968 mètres
Distance entre grand palais et la défense arena : 9777.461 mètres
Distance entre grand palais et stade nautique : 36066.44 mètres
Distance entre grand palais et golf national : 29268.41 mètres
Distance entre grand palais et vélodrome national de saint-quentin-en-yvelines : 32077.74 mètres
Distance entre grand palais et stade roland garros : 7733.461 mètres
Distance entre grand palais et clichy-sous-bois : 26527.01 mètres
Distance entre invalides et site d'escalade du bourget : 14557.86 mètres
Distance entre invalides et pont d'iéna : 2519.929 mètres
Distance entre invalides et arena bercy : 7727.262 mètres
Distance entre invalides et arena paris nord : 25936.7 mètres
Distance entre invalides et arena paris sud 6 (porte de versailles) : 4409.24 mètres
Distance entre invalides et stade de la concorde : 961.6114 mètres
Distance entre invalides et stade yves du manoir : 10391.84 mètres
Distance entre invalides et arena champs de mars : 1666.21 mètres
Distance entre invalides et stade tour eiffel : 1988.892 mètres
Distance entre invalides et stade bmx de saint-quentin-en-yvelines : 32104.64 mètres
Distance entre invalides et arena la chapelle : 6809.104 mètres
Distance entre invalides et stade pierre de coubertin : 6911.713 mètres
Distance entre invalides et centre aquatique : 8274.713 mètres
Distance entre invalides et arena paris sud 1 (porte de versailles) : 4667.773 mètres
Distance entre invalides et arena paris sud 4 (porte de versailles) : 4461.792 mètres
Distance entre invalides et hôtel de ville de paris : 4294.278 mètres
Distance entre invalides et la défense arena : 10010.3 mètres
Distance entre invalides et stade nautique : 35973.12 mètres
Distance entre invalides et golf national : 29170.6 mètres
Distance entre invalides et vélodrome national de saint-quentin-en-yvelines : 32055.06 mètres
Distance entre invalides et stade roland garros : 7720.278 mètres
Distance entre invalides et clichy-sous-bois : 26520.3 mètres
Distance entre site d'escalade du bourget et pont d'iéna : 16954.31 mètres
Distance entre site d'escalade du bourget et arena bercy : 11914.04 mètres
Distance entre site d'escalade du bourget et arena paris nord : 11625.97 mètres
Distance entre site d'escalade du bourget et arena paris sud 6 (porte de versailles) : 18749.97 mètres
Distance entre site d'escalade du bourget et stade de la concorde : 13620.42 mètres
Distance entre site d'escalade du bourget et stade yves du manoir : 19007.54 mètres
Distance entre site d'escalade du bourget et arena champs de mars : 16220.87 mètres
Distance entre site d'escalade du bourget et stade tour eiffel : 16456.19 mètres
Distance entre site d'escalade du bourget et stade bmx de saint-quentin-en-yvelines : 46064.28 mètres
Distance entre site d'escalade du bourget et arena la chapelle : 7761.018 mètres
Distance entre site d'escalade du bourget et stade pierre de coubertin : 21411.54 mètres
Distance entre site d'escalade du bourget et centre aquatique : 7388.643 mètres
Distance entre site d'escalade du bourget et arena paris sud 1 (porte de versailles) : 19158.75 mètres
Distance entre site d'escalade du bourget et arena paris sud 4 (porte de versailles) : 18849.17 mètres
Distance entre site d'escalade du bourget et hôtel de ville de paris : 11786.15 mètres
Distance entre site d'escalade du bourget et la défense arena : 21731.54 mètres
Distance entre site d'escalade du bourget et stade nautique : 25439.3 mètres
Distance entre site d'escalade du bourget et golf national : 43586.04 mètres
Distance entre site d'escalade du bourget et vélodrome national de saint-quentin-en-yvelines : 46006.67 mètres
Distance entre site d'escalade du bourget et stade roland garros : 21892.32 mètres
Distance entre site d'escalade du bourget et clichy-sous-bois : 14313.45 mètres
Distance entre pont d'iéna et arena bercy : 9891.422 mètres
Distance entre pont d'iéna et arena paris nord : 28402.56 mètres
Distance entre pont d'iéna et arena paris sud 6 (porte de versailles) : 2963.77 mètres
Distance entre pont d'iéna et stade de la concorde : 3476.289 mètres
Distance entre pont d'iéna et stade yves du manoir : 9501.775 mètres
Distance entre pont d'iéna et arena champs de mars : 1021.525 mètres
Distance entre pont d'iéna et stade tour eiffel : 532.4663 mètres
Distance entre pont d'iéna et stade bmx de saint-quentin-en-yvelines : 29584.77 mètres
Distance entre pont d'iéna et arena la chapelle : 9194.18 mètres
Distance entre pont d'iéna et stade pierre de coubertin : 4457.281 mètres
Distance entre pont d'iéna et centre aquatique : 10335.35 mètres
Distance entre pont d'iéna et arena paris sud 1 (porte de versailles) : 2810.3 mètres
Distance entre pont d'iéna et arena paris sud 4 (porte de versailles) : 2906.488 mètres
Distance entre pont d'iéna et hôtel de ville de paris : 6681.168 mètres
Distance entre pont d'iéna et la défense arena : 8146.46 mètres
Distance entre pont d'iéna et stade nautique : 38408.06 mètres
Distance entre pont d'iéna et golf national : 26689.83 mètres
Distance entre pont d'iéna et vélodrome national de saint-quentin-en-yvelines : 29535.23 mètres
Distance entre pont d'iéna et stade roland garros : 5205.364 mètres
Distance entre pont d'iéna et clichy-sous-bois : 29035.72 mètres
Distance entre arena bercy et arena paris nord : 21516.85 mètres
Distance entre arena bercy et arena paris sud 6 (porte de versailles) : 9816.295 mètres
Distance entre arena bercy et stade de la concorde : 7046.447 mètres
Distance entre arena bercy et stade yves du manoir : 17616.92 mètres
Distance entre arena bercy et arena champs de mars : 8869.957 mètres
Distance entre arena bercy et stade tour eiffel : 9404.021 mètres
Distance entre arena bercy et stade bmx de saint-quentin-en-yvelines : 38691.77 mètres
Distance entre arena bercy et arena la chapelle : 7016.752 mètres
Distance entre arena bercy et stade pierre de coubertin : 13490.06 mètres
Distance entre arena bercy et centre aquatique : 9773.131 mètres
Distance entre arena bercy et arena paris sud 1 (porte de versailles) : 10530.69 mètres
Distance entre arena bercy et arena paris sud 4 (porte de versailles) : 9992.586 mètres
Distance entre arena bercy et hôtel de ville de paris : 3631.786 mètres
Distance entre arena bercy et la défense arena : 17735.22 mètres
Distance entre arena bercy et stade nautique : 28826.38 mètres
Distance entre arena bercy et golf national : 35064.48 mètres
Distance entre arena bercy et vélodrome national de saint-quentin-en-yvelines : 38651.32 mètres
Distance entre arena bercy et stade roland garros : 14836.32 mètres
Distance entre arena bercy et clichy-sous-bois : 20357.07 mètres
Distance entre arena paris nord et arena paris sud 6 (porte de versailles) : 29913.68 mètres
Distance entre arena paris nord et stade de la concorde : 24979.54 mètres
Distance entre arena paris nord et stade yves du manoir : 30319.07 mètres
Distance entre arena paris nord et arena champs de mars : 27600.34 mètres
Distance entre arena paris nord et stade tour eiffel : 27888.78 mètres
Distance entre arena paris nord et stade bmx de saint-quentin-en-yvelines : 57683.56 mètres
Distance entre arena paris nord et arena la chapelle : 19254.99 mètres
Distance entre arena paris nord et stade pierre de coubertin : 32845.14 mètres
Distance entre arena paris nord et centre aquatique : 18979.71 mètres
Distance entre arena paris nord et arena paris sud 1 (porte de versailles) : 30406.15 mètres
Distance entre arena paris nord et arena paris sud 4 (porte de versailles) : 30034.73 mètres
Distance entre arena paris nord et hôtel de ville de paris : 22601.59 mètres
Distance entre arena paris nord et la défense arena : 33304.5 mètres
Distance entre arena paris nord et stade nautique : 17814.32 mètres
Distance entre arena paris nord et golf national : 55091.12 mètres
Distance entre arena paris nord et vélodrome national de saint-quentin-en-yvelines : 57626.49 mètres
Distance entre arena paris nord et stade roland garros : 33442.15 mètres
Distance entre arena paris nord et clichy-sous-bois : 7341.222 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade de la concorde : 5241.777 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade yves du manoir : 12149.36 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena champs de mars : 2971.343 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade tour eiffel : 3127.157 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade bmx de saint-quentin-en-yvelines : 28889.3 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena la chapelle : 11085.62 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade pierre de coubertin : 3770.201 mètres
Distance entre arena paris sud 6 (porte de versailles) et centre aquatique : 12683.94 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena paris sud 1 (porte de versailles) : 788.7158 mètres
Distance entre arena paris sud 6 (porte de versailles) et arena paris sud 4 (porte de versailles) : 195.7977 mètres
Distance entre arena paris sud 6 (porte de versailles) et hôtel de ville de paris : 7398.72 mètres
Distance entre arena paris sud 6 (porte de versailles) et la défense arena : 10008.33 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade nautique : 38642.2 mètres
Distance entre arena paris sud 6 (porte de versailles) et golf national : 25465.16 mètres
Distance entre arena paris sud 6 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28847.6 mètres
Distance entre arena paris sud 6 (porte de versailles) et stade roland garros : 5410.831 mètres
Distance entre arena paris sud 6 (porte de versailles) et clichy-sous-bois : 29866.16 mètres
Distance entre stade de la concorde et stade yves du manoir : 10763.37 mètres
Distance entre stade de la concorde et arena champs de mars : 2620.806 mètres
Distance entre stade de la concorde et stade tour eiffel : 2946.9 mètres
Distance entre stade de la concorde et stade bmx de saint-quentin-en-yvelines : 33058.49 mètres
Distance entre stade de la concorde et arena la chapelle : 5885.3 mètres
Distance entre stade de la concorde et stade pierre de coubertin : 7871.815 mètres
Distance entre stade de la concorde et centre aquatique : 7485.05 mètres
Distance entre stade de la concorde et arena paris sud 1 (porte de versailles) : 5562.295 mètres
Distance entre stade de la concorde et arena paris sud 4 (porte de versailles) : 5312.2 mètres
Distance entre stade de la concorde et hôtel de ville de paris : 3500.37 mètres
Distance entre stade de la concorde et la défense arena : 10720.35 mètres
Distance entre stade de la concorde et stade nautique : 35086.44 mètres
Distance entre stade de la concorde et golf national : 30131.23 mètres
Distance entre stade de la concorde et vélodrome national de saint-quentin-en-yvelines : 33008.62 mètres
Distance entre stade de la concorde et stade roland garros : 8668.867 mètres
Distance entre stade de la concorde et clichy-sous-bois : 25575.8 mètres
Distance entre stade yves du manoir et arena champs de mars : 10188.13 mètres
Distance entre stade yves du manoir et stade tour eiffel : 9674.774 mètres
Distance entre stade yves du manoir et stade bmx de saint-quentin-en-yvelines : 28784.98 mètres
Distance entre stade yves du manoir et arena la chapelle : 12943.9 mètres
Distance entre stade yves du manoir et stade pierre de coubertin : 10679.74 mètres
Distance entre stade yves du manoir et centre aquatique : 11794.35 mètres
Distance entre stade yves du manoir et arena paris sud 1 (porte de versailles) : 11634.33 mètres
Distance entre stade yves du manoir et arena paris sud 4 (porte de versailles) : 12018.71 mètres
Distance entre stade yves du manoir et hôtel de ville de paris : 13987.19 mètres
Distance entre stade yves du manoir et la défense arena : 4512.378 mètres
Distance entre stade yves du manoir et stade nautique : 43701.24 mètres
Distance entre stade yves du manoir et golf national : 27836.06 mètres
Distance entre stade yves du manoir et vélodrome national de saint-quentin-en-yvelines : 28713.33 mètres
Distance entre stade yves du manoir et stade roland garros : 9306.441 mètres
Distance entre stade yves du manoir et clichy-sous-bois : 33085.35 mètres
Distance entre arena champs de mars et stade tour eiffel : 567.5872 mètres
Distance entre arena champs de mars et stade bmx de saint-quentin-en-yvelines : 30507.17 mètres
Distance entre arena champs de mars et arena la chapelle : 8467.326 mètres
Distance entre arena champs de mars et stade pierre de coubertin : 5254.769 mètres
Distance entre arena champs de mars et centre aquatique : 9818.745 mètres
Distance entre arena champs de mars et arena paris sud 1 (porte de versailles) : 3087.526 mètres
Distance entre arena champs de mars et arena paris sud 4 (porte de versailles) : 2981.165 mètres
Distance entre arena champs de mars et hôtel de ville de paris : 5683.388 mètres
Distance entre arena champs de mars et la défense arena : 9103.359 mètres
Distance entre arena champs de mars et stade nautique : 37408.79 mètres
Distance entre arena champs de mars et golf national : 27514.28 mètres
Distance entre arena champs de mars et vélodrome national de saint-quentin-en-yvelines : 30458.76 mètres
Distance entre arena champs de mars et stade roland garros : 6165.247 mètres
Distance entre arena champs de mars et clichy-sous-bois : 28098.06 mètres
Distance entre stade tour eiffel et stade bmx de saint-quentin-en-yvelines : 30116.34 mètres
Distance entre stade tour eiffel et arena la chapelle : 8695.175 mètres
Distance entre stade tour eiffel et stade pierre de coubertin : 4960.72 mètres
Distance entre stade tour eiffel et centre aquatique : 9901.803 mètres
Distance entre stade tour eiffel et arena paris sud 1 (porte de versailles) : 3099.422 mètres
Distance entre stade tour eiffel et arena paris sud 4 (porte de versailles) : 3101.604 mètres
Distance entre stade tour eiffel et hôtel de ville de paris : 6159.559 mètres
Distance entre stade tour eiffel et la défense arena : 8536.047 mètres
Distance entre stade tour eiffel et stade nautique : 37884.99 mètres
Distance entre stade tour eiffel et golf national : 27206.09 mètres
Distance entre stade tour eiffel et vélodrome national de saint-quentin-en-yvelines : 30066.88 mètres
Distance entre stade tour eiffel et stade roland garros : 5737.797 mètres
Distance entre stade tour eiffel et clichy-sous-bois : 28503.27 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena la chapelle : 38489.51 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade pierre de coubertin : 25348.99 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et centre aquatique : 38791.12 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena paris sud 1 (porte de versailles) : 28205.86 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et arena paris sud 4 (porte de versailles) : 28719.15 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et hôtel de ville de paris : 36092.63 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et la défense arena : 24829.22 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade nautique : 67491.12 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et golf national : 6098.004 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et vélodrome national de saint-quentin-en-yvelines : 91.69166 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et stade roland garros : 24394.96 mètres
Distance entre stade bmx de saint-quentin-en-yvelines et clichy-sous-bois : 58601.78 mètres
Distance entre arena la chapelle et stade pierre de coubertin : 13651.43 mètres
Distance entre arena la chapelle et centre aquatique : 2756.517 mètres
Distance entre arena la chapelle et arena paris sud 1 (porte de versailles) : 11445.37 mètres
Distance entre arena la chapelle et arena paris sud 4 (porte de versailles) : 11170.78 mètres
Distance entre arena la chapelle et hôtel de ville de paris : 4879.972 mètres
Distance entre arena la chapelle et la défense arena : 14710.67 mètres
Distance entre arena la chapelle et stade nautique : 30844.63 mètres
Distance entre arena la chapelle et golf national : 35852.22 mètres
Distance entre arena la chapelle et vélodrome national de saint-quentin-en-yvelines : 38434.83 mètres
Distance entre arena la chapelle et stade roland garros : 14187.33 mètres
Distance entre arena la chapelle et clichy-sous-bois : 20589.85 mètres
Distance entre stade pierre de coubertin et centre aquatique : 14692.67 mètres
Distance entre stade pierre de coubertin et arena paris sud 1 (porte de versailles) : 2998.992 mètres
Distance entre stade pierre de coubertin et arena paris sud 4 (porte de versailles) : 3578.044 mètres
Distance entre stade pierre de coubertin et hôtel de ville de paris : 10744.47 mètres
Distance entre stade pierre de coubertin et la défense arena : 7400.604 mètres
Distance entre stade pierre de coubertin et stade nautique : 42298.61 mètres
Distance entre stade pierre de coubertin et golf national : 22259.76 mètres
Distance entre stade pierre de coubertin et vélodrome national de saint-quentin-en-yvelines : 25303.44 mètres
Distance entre stade pierre de coubertin et stade roland garros : 1890.523 mètres
Distance entre stade pierre de coubertin et clichy-sous-bois : 33267.48 mètres
Distance entre centre aquatique et arena paris sud 1 (porte de versailles) : 12903.64 mètres
Distance entre centre aquatique et arena paris sud 4 (porte de versailles) : 12734.24 mètres
Distance entre centre aquatique et hôtel de ville de paris : 7421.643 mètres
Distance entre centre aquatique et la défense arena : 14343.1 mètres
Distance entre centre aquatique et stade nautique : 31996.71 mètres
Distance entre centre aquatique et golf national : 36558.83 mètres
Distance entre centre aquatique et vélodrome national de saint-quentin-en-yvelines : 38731.36 mètres
Distance entre centre aquatique et stade roland garros : 14890.71 mètres
Distance entre centre aquatique et clichy-sous-bois : 21291.13 mètres
Distance entre arena paris sud 1 (porte de versailles) et arena paris sud 4 (porte de versailles) : 592.9181 mètres
Distance entre arena paris sud 1 (porte de versailles) et hôtel de ville de paris : 7981.963 mètres
Distance entre arena paris sud 1 (porte de versailles) et la défense arena : 9312.84 mètres
Distance entre arena paris sud 1 (porte de versailles) et stade nautique : 39355.28 mètres
Distance entre arena paris sud 1 (porte de versailles) et golf national : 24868.19 mètres
Distance entre arena paris sud 1 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28163.04 mètres
Distance entre arena paris sud 1 (porte de versailles) et stade roland garros : 4622.308 mètres
Distance entre arena paris sud 1 (porte de versailles) et clichy-sous-bois : 30492.85 mètres
Distance entre arena paris sud 4 (porte de versailles) et hôtel de ville de paris : 7539.999 mètres
Distance entre arena paris sud 4 (porte de versailles) et la défense arena : 9834.345 mètres
Distance entre arena paris sud 4 (porte de versailles) et stade nautique : 38818.94 mètres
Distance entre arena paris sud 4 (porte de versailles) et golf national : 25316.01 mètres
Distance entre arena paris sud 4 (porte de versailles) et vélodrome national de saint-quentin-en-yvelines : 28677.18 mètres
Distance entre arena paris sud 4 (porte de versailles) et stade roland garros : 5215.075 mètres
Distance entre arena paris sud 4 (porte de versailles) et clichy-sous-bois : 30021 mètres
Distance entre hôtel de ville de paris et la défense arena : 14218.99 mètres
Distance entre hôtel de ville de paris et stade nautique : 31727.11 mètres
Distance entre hôtel de ville de paris et golf national : 32849.18 mètres
Distance entre hôtel de ville de paris et vélodrome national de saint-quentin-en-yvelines : 36046.69 mètres
Distance entre hôtel de ville de paris et stade roland garros : 11837.93 mètres
Distance entre hôtel de ville de paris et clichy-sous-bois : 22530.34 mètres
Distance entre la défense arena et stade nautique : 45422.07 mètres
Distance entre la défense arena et golf national : 23490.01 mètres
Distance entre la défense arena et vélodrome national de saint-quentin-en-yvelines : 24762.46 mètres
Distance entre la défense arena et stade roland garros : 5657.121 mètres
Distance entre la défense arena et clichy-sous-bois : 35295.47 mètres
Distance entre stade nautique et golf national : 63604.35 mètres
Distance entre stade nautique et vélodrome national de saint-quentin-en-yvelines : 67452.65 mètres
Distance entre stade nautique et stade roland garros : 43543.37 mètres
Distance entre stade nautique et clichy-sous-bois : 11400.29 mètres
Distance entre golf national et vélodrome national de saint-quentin-en-yvelines : 6135.202 mètres
Distance entre golf national et stade roland garros : 21703.18 mètres
Distance entre golf national et clichy-sous-bois : 55319.43 mètres
Distance entre vélodrome national de saint-quentin-en-yvelines et stade roland garros : 24344.29 mètres
Distance entre vélodrome national de saint-quentin-en-yvelines et clichy-sous-bois : 58554.14 mètres
Distance entre stade roland garros et clichy-sous-bois : 34240.23 mètres</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(site1) <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="fu">is.null</span>(site2)) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Les deux sites les plus proches en distance sont :"</span>, site3, <span class="st">"et"</span>, site4, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Les deux sites les plus proches en distance sont : colline d'elancourt et stade nautique </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(distance_min)) {</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"La distance entre ces deux sites va être de :"</span>, distance_max, <span class="st">"mètres</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La distance entre ces deux sites va être de : 74882.55 mètres</code></pre>
</div>
</div>
<p><em>Les deux sites les plus proches en distance sont : colline d’elancourt et stade nautique et la distance entre ces deux sites va être de : 74882.55 mètres</em></p>
<p><strong>Question 11 :</strong> Vous êtes un heureux millionaire et souhaitez investir dans un bien immobilier. Vous décidez d’acheter un appartement situé au barycentre de l’ensemble des sites olympiques. Où se situe cet appartement ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(coordonnees<span class="sc">$</span>latitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48.86684</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(coordonnees<span class="sc">$</span>longitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.29757</code></pre>
</div>
</div>
<p><em>Cette appartement si situe à 48.86684 en latitude et 2.29757 en longitude</em></p>
<p><br>
</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>